//LOGIN
import {PERMISSIONS} from "react-native-permissions";

export const SET_ERROR = 'SET_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const BLOCK_QR_APPEARING = 'BLOCK_QR_APPEARING';
export const BLOCK_ELEMENT_APPEARING = 'BLOCK_ELEMENT_APPEARING';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';


export const JOIN_TO_GAME_REQUEST = 'JOIN_TO_GAME_REQUEST';
export const JOIN_TO_GAME_REQUEST_SUCCESS = 'JOIN_TO_GAME_REQUEST_SUCCESS';
export const JOIN_TO_GAME_REQUEST_FAIL = 'JOIN_TO_GAME_REQUEST_FAIL';

export const START_GAME_REQUEST = 'START_GAME_REQUEST';
export const START_GAME_REQUEST_SUCCESS = 'START_GAME_REQUEST_SUCCESS';
export const START_GAME_REQUEST_FAIL = 'START_GAME_REQUEST_FAIL';

export const GET_USER_ACTIVE_GAME_REQUEST = 'GET_USER_ACTIVE_GAME_REQUEST';
export const GET_USER_ACTIVE_GAME_REQUEST_SUCCESS = 'GET_USER_ACTIVE_GAME_REQUEST_SUCCESS';
export const GET_USER_ACTIVE_GAME_REQUEST_FAIL = 'GET_USER_ACTIVE_GAME_REQUEST_FAIL';

export const CHANGE_SCREEN_ORIENTATION = 'CHANGE_SCREEN_ORIENTATION';

export const NEW_JOIN = 'NEW_JOIN';
export const START_GAME = 'START_GAME';
export const RIDDLE_SOLVED = 'RIDDLE_SOLVED';
export const TAKE_ELEMENT = 'TAKE_ELEMENT';
export const GAME_OVER = 'GAME_OVER';
export const SET_PERMISSIONS = 'SET_PERMISSIONS';

export const SET_SCREEN_LOADER_VISIBLE = 'SET_SCREEN_LOADER_VISIBLE';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SOW_QR_CODE = 'SOW_QR_CODE';
export const HIDE_QR_CODE = 'HIDE_QR_CODE';

export const SOW_ELEMENT = 'SOW_ELEMENT';
export const HIDE_ELEMENT = 'HIDE_ELEMENT';

export const SOW_MOZART = 'SOW_MOZART';
export const HIDE_MOZART = 'HIDE_MOZART';

export const SHOW_MODAL_ELEMENT = 'SHOW_MODAL_ELEMENT';
export const HIDE_MODAL_ELEMENT = 'HIDE_MODAL_ELEMENT';

export const MAKE_CAMERA_VISIBLE = 'MAKE_CAMERA_VISIBLE';
export const MAKE_CAMERA_INVISIBLE = 'MAKE_CAMERA_INVISIBLE';


export const RIDDLE_SOLVED_REQUEST = 'RIDDLE_SOLVED_REQUEST';
export const RIDDLE_SOLVED_REQUEST_SUCCESS = 'RIDDLE_SOLVED_REQUEST_SUCCESS';
export const RIDDLE_SOLVED_REQUEST_FAIL = 'RIDDLE_SOLVED_REQUEST_FAIL';

export const TAKE_ELEMENT_REQUEST = 'TAKE_ELEMENT_REQUEST';
export const TAKE_ELEMENT_REQUEST_SUCCESS = 'TAKE_ELEMENT_REQUEST_SUCCESS';
export const TAKE_ELEMENT_REQUEST_FAIL = 'TAKE_ELEMENT_REQUEST_FAIL';

export const CORRECT_ELEMENT_REQUEST = 'CORRECT_ELEMENT_REQUEST';
export const CORRECT_ELEMENT_REQUEST_SUCCESS = 'CORRECT_ELEMENT_REQUEST_SUCCESS';
export const CORRECT_ELEMENT_REQUEST_FAIL = 'CORRECT_ELEMENT_REQUEST_FAIL';

export const CUP_ACTIVATE_REQUEST = 'CUP_ACTIVATE_REQUEST';
export const CUP_ACTIVATE_REQUEST_SUCCESS = 'CUP_ACTIVATE_REQUEST_SUCCESS';
export const CUP_ACTIVATE_REQUEST_FAIL = 'CUP_ACTIVATE_REQUEST_FAIL';

export const ELEMENT_ACTIVATE_REQUEST = 'ELEMENT_ACTIVATE_REQUEST';
export const ELEMENT_ACTIVATE_REQUEST_SUCCESS = 'ELEMENT_ACTIVATE_REQUEST_SUCCESS';
export const ELEMENT_ACTIVATE_REQUEST_FAIL = 'ELEMENT_ACTIVATE_REQUEST_FAIL';

export const UPDATE_LOGIC_RIDDLE_REQUEST = 'UPDATE_LOGIC_RIDDLE_REQUEST';
export const UPDATE_LOGIC_RIDDLE_REQUEST_SUCCESS = 'UPDATE_LOGIC_RIDDLE_REQUEST_SUCCESS';
export const UPDATE_LOGIC_RIDDLE_REQUEST_FAIL = 'UPDATE_LOGIC_RIDDLE_REQUEST_FAIL';


// TEST
export const REMOVE_USER_JOINS_REQUEST = 'REMOVE_USER_JOINS_REQUEST';
export const REMOVE_USER_JOINS_REQUEST_SUCCESS = 'REMOVE_USER_JOINS_REQUEST_SUCCESS';
export const REMOVE_USER_JOINS_REQUEST_FAIL = 'REMOVE_USER_JOINS_REQUEST_FAIL';








